_core:
  default_config_hash: zMBMF9Q35kIhZL2P1Dztk-BGFewINdrs8RE9bB5kqyo
  admin_css: true
one_pixel: true
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: null
responsive_image: true
