_core:
  default_config_hash: IcQHew9bl7VAvj5XR81tqe8fDjfZm7TydSzuASRfSCs
country:
  default: US
first_day: 0
timezone:
  default: America/New_York
  user:
    configurable: true
    warn: false
    default: 0
